imports:
    - { resource: "../packages/*/config/*.yaml" }

# set for coding standard services, excepts sniffs and fixers
services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    # see https://github.com/symplify/codingstandard to see all loaded Symplify checkers
    Symplify\CodingStandard\:
        resource: '../src'
        # checkers that needs configuration to run
        exclude:
            - '../src/TokenRunner/ValueObject/*'
            - '../src/Sniffs/*'
            - '../src/Fixer/*'
            - '../src/Rules/*'

    PhpCsFixer\Tokenizer\Analyzer\FunctionsAnalyzer: null
    PhpCsFixer\WhitespacesFixerConfig: null

    Symplify\EasyCodingStandard\ChangedFilesDetector\ChangedFilesDetector: null
