services:
    _defaults:
        autowire: true
        public: true

    Symplify\CodingStandard\TokenRunner\:
        resource: "../src"
        exclude:
            - "../src/ValueObject/*"

    Symplify\PackageBuilder\Types\ClassLikeExistenceChecker: ~
    PhpCsFixer\Tokenizer\Analyzer\FunctionsAnalyzer: ~

    PHPStan\PhpDocParser\Parser\PhpDocParser: ~
    PHPStan\PhpDocParser\Parser\TypeParser: ~
    PHPStan\PhpDocParser\Parser\ConstExprParser: ~
    PHPStan\PhpDocParser\Lexer\Lexer: ~
